### ISSUE TITLE
Cairo problem?  minus symbol $-$ missing when exported as eps or pdf file from iperender

### ISSUE THREAD

**Issue by angeugdong** [otfried/ipe#122]
tested OS: Fedora 25 & CentOS 7
tested Ipe Version: 7.2.6 & 7.2.7 

For a figure containing symbol $-$, when it is exported as .eps file, the symbol will be missing. No problems when saved in .ipe or .pdf format, or exported as .png file.

**Comment by frececroka** [comment]
Is there any update on this? I am also experiencing the same issue with Ipe 7.2.7 on a current Arch Linux.

**Comment by otfried** [comment]
I simply cannot reproduce this.   Can you attach a file that exhibits the problem?   Also, what is the output of
```
ipe  -show-configuration
```
The contents of the *About Ipe* window would also be helpful.

**Comment by otfried** [comment]
I'd also be interested in knowing why you still need eps output.   Since nearly everybody has switched to a PDF-based workflow, the EPS export is not well tested (I never use it myself).

**Comment by angeugdong** [comment]
Here is an example. The $-$ symbol in the table does not shown in exported eps file.
[star.zip](https://github.com/otfried/ipe-issues/files/2751950/star.zip)

**Comment by angeugdong** [comment]
> I simply cannot reproduce this. Can you attach a file that exhibits the problem? Also, what is the output of
> 
> ```
> ipe  -show-configuration
> ```
> The contents of the _About Ipe_ window would also be helpful.

Test the file in the tarball and you will see the problem. By the way, we use eps file because our PhD advisor requires this, that is all.
[star.zip](https://github.com/otfried/ipe-issues/files/2751951/star.zip)

**Comment by angeugdong** [comment]
> I simply cannot reproduce this. Can you attach a file that exhibits the problem? Also, what is the output of
> 
> ```
> ipe  -show-configuration
> ```
> The contents of the _About Ipe_ window would also be helpful.

Moreover, the command gives the following output:

Ipe 7.2.7
Lua code: /opt/ipe/7.2.7/share/ipe/7.2.7/lua/?.lua
Style directories: /home/yan/.ipe/styles, /opt/ipe/7.2.7/share/ipe/7.2.7/styles
Styles for new documents: basic
Autosave file: /home/yan/%s.autosave
Save-as directory: .
Documentation: /opt/ipe/7.2.7/share/ipe/7.2.7/doc
Ipelets: /opt/ipe/7.2.7/lib/ipe/7.2.7/ipelets, /home/yan/.ipe/ipelets
Latex program path: 
Latex directory: /home/yan/.ipe/latexrun/
Icons: /opt/ipe/7.2.7/share/ipe/7.2.7/icons/
External editor: none

**Comment by otfried** [comment]
It turns out this is a known bug in Cairo 1.14: https://bugs.launchpad.net/ubuntu/+source/cairo/+bug/1734092

The problem has been fixed in Cairo 1.15 (which is the reason I couldn't reproduce it on my Mint 19 system).

I need to upgrade the Cairo version I use for the Windows and OSX binaries...

You can download the Ipe AppImage (https://download.opensuse.org/repositories/home:/otfried13/AppImage/ipe-latest-x86_64.AppImage) and run that on your system - it is built with Cairo 1.15.2.   To do the conversion, you can use:
```
chmod 0755 ipe-0-Build26.1.glibc2.14-x86_64.AppImage
./ipe-0-Build26.1.glibc2.14-x86_64.AppImage iperender -eps star.ipe star.eps
```

Otherwise you could try to save as PDF and run one of the many pdt to ps converters (e.g. pdftops).

**Comment by angeugdong** [comment]
> It turns out this is a known bug in Cairo 1.14: https://bugs.launchpad.net/ubuntu/+source/cairo/+bug/1734092
> 
> The problem has been fixed in Cairo 1.15 (which is the reason I couldn't reproduce it on my Mint 19 system).
> 
> I need to upgrade the Cairo version I use for the Windows and OSX binaries...
> 
> You can download the Ipe AppImage (https://download.opensuse.org/repositories/home:/otfried13/AppImage/ipe-latest-x86_64.AppImage) and run that on your system - it is built with Cairo 1.15.2. To do the conversion, you can use:
> 
> ```
> chmod 0755 ipe-0-Build26.1.glibc2.14-x86_64.AppImage
> ./ipe-0-Build26.1.glibc2.14-x86_64.AppImage iperender -eps star.ipe star.eps
> ```
> Otherwise you could try to save as PDF and run one of the many pdt to ps converters (e.g. pdftops).

Dear Otfried, Thank you very much! I actually have cairo-1.15.12-3 installed in my CentOS 7, it's weird I still have the problem.

**Comment by otfried** [comment]
Unfortunately, upgrading to Cairo 1.16.0 also did not fix the problem for me on Windows.   I'll need to investigate further...

**Comment by otfried** [comment]
Apparently this has something to do with this feature:
https://gitlab.freedesktop.org/cairo/cairo/commit/495362279b42620071c6b46f69918ce324aee0db

Cairo cannot render glyph index zero: "The cmap we use for embedding latin fonts does not allow rendering glyph 0."  

The hyphen is at glyph index zero.  For some reason, the code here does not remap it to a different index.  When running the pdf through pdftocairo, it works correctly...

**Comment by otfried** [comment]
It does seem to be a Cairo problem:  In `cairo-scaled-font-subsets.c`, there is special treatment for the character with character code 0.  It seems this treatment does not work if it is not the first character from this font being used.

**Working around the bug:**
So you can actually work around the bug by adding a text label with contents `$-$` to your document and moving it into the background (Ctrl+B), so that it is drawn first. You can make its color white, so that it remains invisible.

I will make a short demo program to demonstrate the bug and report the problem to Cairo.

**Comment by otfried** [comment]
I've reported the problem to Cairo at https://gitlab.freedesktop.org/cairo/cairo/issues/354.

Let's see if they have a fix for us or if we need to wait for a fix in Cairo.

Here is again the demo code: 
```
//
// Demonstrate problem with character code 0 in Cairo
//
// Compile with
// clang++-6.0 -o demo `pkg-config --cflags --libs cairo freetype2` demo.cpp

#include <iostream>
#include <vector>

#include <ft2build.h>
#include FT_FREETYPE_H

#include <cairo.h>
#include <cairo-ft.h>
#include <cairo-pdf.h>

int main(int argc, char **argv)
{
  if (argc != 4) {
    std::cerr << "Usage: ./demo <font.pfb> <charcode1> <charcode2>" << std::endl;
    return -1;
  }
  const char *fontfile = argv[1];
  int code1 = strtod(argv[2], NULL);
  int code2 = strtod(argv[3], NULL);

  FT_Library lib;
  if (FT_Init_FreeType(&lib))
    return 99;
  FT_Face face;
  if (FT_New_Face(lib, "cmsy10.pfb", 0, &face))
    return 98;

  for (int k = 0; k < face->num_charmaps; ++k) {
    if (face->charmaps[k]->encoding == FT_ENCODING_ADOBE_CUSTOM) {
      FT_Set_Charmap(face, face->charmaps[k]);
      break;
    }
  }
    
  cairo_font_face_t *font = cairo_ft_font_face_create_for_ft_face(face, 0);
  
  cairo_surface_t* surface = cairo_pdf_surface_create("test.pdf", 300.0, 200.0);
  if (surface == nullptr)
    return 97;
  cairo_t *cc = cairo_create(surface);

  std::vector<cairo_glyph_t> glyphs;

  cairo_glyph_t g;
  g.index = FT_Get_Char_Index(face, code1);
  g.x = 100;
  g.y = 40;
  glyphs.push_back(g);
  g.index = FT_Get_Char_Index(face, code2);
  g.x = 130;
  g.y = 40;
  glyphs.push_back(g);
    
  cairo_set_font_face(cc, font);
  cairo_matrix_t matrix { 10.0, 0.0, 0.0, 10.0, 0.0, 0.0 };
  cairo_set_font_matrix(cc, &matrix);
  cairo_show_glyphs(cc, &glyphs[0], glyphs.size());

  cairo_surface_flush(surface);
  cairo_show_page(cc);
  cairo_destroy(cc);
  cairo_surface_destroy(surface);
  FT_Done_FreeType(lib);
  std::cerr << "All done" << std::endl;
  return 0;
}
```

Running as:
```
$ ./demo cmsy10.pfb 0 110
```
works, running as
```
$ ./demo cmsy10.pfb 110 0
```
skips the minus glyph.

**Comment by otfried** [comment]
It turns out Ipe can work around the bug by finding glyph indices using the glyph name and the Postscript encoding array, so I've fixed it for 7.2.9.

**Comment by otfried** [comment]
I have rebuilt the Linux appimage with the fix.
