### ISSUE TITLE
Ipe move graph nodes feature does not work after file reopen.

### ISSUE THREAD

**Issue by nikolatzotchev** [otfried/ipe#487]
I tried using Ipe for graphs, the **move graph nodes** feature works great, but then I encountered the problem that  when I save my file (as .pdf or .ipe) and then reopen it, the feature works 50% of the time, very often only the node is moved.
I asked some people to test and on their machines this works (maybe a problem only on fedora, but this does not make sense).
I am using Ipe 7.2.26 on Fedora 38 (tested also on 7.2.28 on another machine using Fedora 39 and It also does not work). I also tried on a windows machine and there the feature seems to work after reopen (but I prefer Linux so that is not an option).

I do not think that I am doing something wrong because the feature works perfectly before reopening the file.
Let me now if you need any other information.

**Comment by nikolatzotchev** [comment]
https://github.com/otfried/ipe/assets/14894154/42465dbd-ded8-4fcc-8d6c-26f19d10592f

**Comment by nikolatzotchev** [comment]
https://github.com/otfried/ipe/assets/14894154/1be86194-9cda-45d9-8a33-77f773e779e8

I was wrong it happens also on no restart, sometimes the node is just moved by itself without the vertices.

**Comment by otfried** [comment]
The problem is caused by rounding errors, because the vertices you are using are markers, which have a bounding box of width zero.  (The problem doesn't happen with small disks etc.)

It'll be fixed in 7.2.29.

**Comment by nikolatzotchev** [comment]
> (The problem doesn't happen with small disks etc.)

If by small disks you mean this setup for Marks:
![2023-11-16-112806_grim](https://github.com/otfried/ipe/assets/14894154/6780022c-d7a3-41a9-8983-18d03abad71f)
I still have the same problem.
(Sorry if you mean something else, I am quite new to Ipe, I just want to have a temporal solution until 7.2.29)

**Comment by otfried** [comment]
No, I meant when you draw a small disk with the circle tool.  I often do that because I need to put a label inside the node.

But I can also just make a new version available where the problem is fixed.   Are you on Windows?

**Comment by nikolatzotchev** [comment]
No I am using linux (fedora) I tried, building it from source, but did not succeed :). 
~~> /lib64/libQt6Core.so: undefined reference to `std::__exception_ptr::exception_ptr::_M_addref()@CXXABI_1.3.13'~~
~~this is the error I am getting
https://gist.github.com/nikolatzotchev/787f215dded8acce3faab0dcc4e229ba~~

**Comment by nikolatzotchev** [comment]
I finally installed it from source, and it works, thank you very much, I will be waiting for the official 7.2.29! Great tool!

**Comment by otfried** [comment]
You mean you compiled the current version from github?   Very good.

**Comment by nikolatzotchev** [comment]
Yes, and from the limited testing I did, It works perfectly. I will use it until the official one will be updated.
